env:
  global:
    - MOZ_HEADLESS=1

stages:
  - "Quality"
  - "Tests"

jobs:
  include:
    - stage: "Quality"
      name: "Frontend Linting"
      language: node_js
      node_js: "8"
      cache:
        yarn: true

      script: ./run yarn && ./run yarn lint --quiet

    - stage: "Quality"
      name: "Frontend Typechecking"
      language: node_js
      node_js: "8"
      cache:
        yarn: true

      script: ./run yarn && ./run yarn tsc --noEmit

    - stage: "Tests"
      name: "Frontend Tests"
      addons:
        chrome: stable

      language: node_js
      node_js: "8"
      cache:
        yarn: true

      # TODO: upload coverage to somewhere
      script: COVERAGE=true ./run yarn && ./run yarn test:ci

    - stage: "External Partner Tests"
      name: "SIL International: Scriptoria"
      language: node_js
      node_js: "8"
      addons:
        apt:
          packages:
            - jq
      script: ./scripts/partner-tests/scriptoria.sh
